version: '3.7'

services:

  app_next:
    image: node:18-buster-slim
    container_name: app_next
    restart: always
    # command: bash -c "yarn install"
    # command: yarn dev
    volumes:
      - ./app/next:/usr/src/app
    working_dir: /usr/src/app
    expose:
      - '3000'
    # networks:
    #   red:
    #     ipv4_address: 10.3.0.10
    env_file: ./app/next/.env
    environment:
      # VIRTUAL_HOST: app.${DOMAIN}
      VIRTUAL_PORT: 3000
    depends_on:
      - api_django


  api_django:
    image: python:3.9.16-alpine3.18
    container_name: api_django
    restart: always
    # command: python manage.py runserver 0.0.0.0:8000
    env_file: ./api/django/.env
    ports:
      - "8000:8000"
    volumes:
      - ./api/django:/app
    working_dir: /app
    # networks:
    #   red:
    #     ipv4_address: 10.3.0.20
    depends_on:
      - api_postgres

  api_postgres:
    image: postgres:13.11
    container_name: api_postgres
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    # networks:
    #   red:
    #     ipv4_address: 10.3.0.21
    volumes:
      - ./api/postgres:/var/lib/postgresql/data

    